/*
 * TJVD License (TJ Valentine’s Discretionary License) — Version 1.0 (2025)
 *
 * Copyright (c) 2025 Taheesh Valentine
 *
 * This source code is protected under the TJVD License.
 * SEE LICENSE.TXT
 */

package org.tavall.dependency.access;

import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.Writer;
import java.util.List;

/**
 * Emits companion metadata classes for granted dependency access descriptors.
 */
public final class DependencyAccessMetadataEmitter {

    /**
     * Emits a companion metadata class with repeated {@code @GrantedDependencyAccess} annotations.
     *
     * @param filer the annotation-processing filer
     * @param messager the annotation-processing messager
     * @param sourceElement the source element that owns the metadata
     * @param descriptors the normalized grant descriptors to emit
     */
    public void emitMetadata(
            Filer filer,
            Messager messager,
            TypeElement sourceElement,
            List<DependencyAccessGrantDescriptor> descriptors) {
        if (filer == null || messager == null || sourceElement == null || descriptors == null || descriptors.isEmpty()) {
            return;
        }

        String packageName = getPackageName(sourceElement);
        String sourceSimpleName = sourceElement.getSimpleName().toString();
        String generatedSimpleName = sourceSimpleName + "DependencyAccessMetadata";
        String generatedQualifiedName = packageName.isBlank()
                ? generatedSimpleName
                : packageName + "." + generatedSimpleName;

        try {
            JavaFileObject sourceFile = filer.createSourceFile(generatedQualifiedName, sourceElement);
            try (Writer writer = sourceFile.openWriter()) {
                if (!packageName.isBlank()) {
                    writer.write("package " + packageName + ";\n\n");
                }

                writer.write("/* Generated by DependencyAccessMetadataEmitter. */\n");
                for (DependencyAccessGrantDescriptor descriptor : descriptors) {
                    writer.write("@org.tavall.dependency.annotations.GrantedDependencyAccess(\n");
                    writer.write("        accessType = " + descriptor.accessType().getCanonicalName() + ".class,\n");
                    writer.write("        dependencyTypes = {");

                    List<Class<?>> dependencyTypes = descriptor.dependencyTypes();
                    for (int index = 0; index < dependencyTypes.size(); index++) {
                        Class<?> dependencyType = dependencyTypes.get(index);
                        if (index > 0) {
                            writer.write(", ");
                        }
                        writer.write("\n                " + dependencyType.getCanonicalName() + ".class");
                    }
                    if (!dependencyTypes.isEmpty()) {
                        writer.write("\n        ");
                    }
                    writer.write("}\n");
                    writer.write(")\n");
                }

                writer.write("final class " + generatedSimpleName + " {\n");
                writer.write("    private " + generatedSimpleName + "() {\n");
                writer.write("    }\n");
                writer.write("}\n");
            }
        } catch (IOException exception) {
            messager.printMessage(
                    Diagnostic.Kind.ERROR,
                    "Failed to emit dependency-access metadata for " + sourceElement.getQualifiedName() + ": "
                            + exception.getMessage(),
                    sourceElement);
        }
    }

    /**
     * Emits a companion metadata class from source-level grant descriptors.
     *
     * @param filer the annotation-processing filer
     * @param messager the annotation-processing messager
     * @param sourceElement the source element that owns the metadata
     * @param descriptors the normalized grant descriptors to emit
     */
    public void emitMetadata(
            Filer filer,
            Messager messager,
            TypeElement sourceElement,
            List<DependencyAccessSourceGrantDescriptor> descriptors,
            boolean sourceDescriptorMode) {
        if (!sourceDescriptorMode) {
            return;
        }
        if (filer == null || messager == null || sourceElement == null || descriptors == null || descriptors.isEmpty()) {
            return;
        }

        String packageName = getPackageName(sourceElement);
        String sourceSimpleName = sourceElement.getSimpleName().toString();
        String generatedSimpleName = sourceSimpleName + "DependencyAccessMetadata";
        String generatedQualifiedName = packageName.isBlank()
                ? generatedSimpleName
                : packageName + "." + generatedSimpleName;

        try {
            JavaFileObject sourceFile = filer.createSourceFile(generatedQualifiedName, sourceElement);
            try (Writer writer = sourceFile.openWriter()) {
                if (!packageName.isBlank()) {
                    writer.write("package " + packageName + ";\n\n");
                }

                writer.write("/* Generated by DependencyAccessMetadataEmitter. */\n");
                for (DependencyAccessSourceGrantDescriptor descriptor : descriptors) {
                    writer.write("@org.tavall.dependency.annotations.GrantedDependencyAccess(\n");
                    writer.write("        accessType = " + descriptor.accessType() + ".class,\n");
                    writer.write("        dependencyTypes = {");

                    List<String> dependencyTypes = descriptor.dependencyTypes();
                    for (int index = 0; index < dependencyTypes.size(); index++) {
                        String dependencyType = dependencyTypes.get(index);
                        if (index > 0) {
                            writer.write(", ");
                        }
                        writer.write("\n                " + dependencyType + ".class");
                    }
                    if (!dependencyTypes.isEmpty()) {
                        writer.write("\n        ");
                    }
                    writer.write("}\n");
                    writer.write(")\n");
                }

                writer.write("final class " + generatedSimpleName + " {\n");
                writer.write("    private " + generatedSimpleName + "() {\n");
                writer.write("    }\n");
                writer.write("}\n");
            }
        } catch (IOException exception) {
            messager.printMessage(
                    Diagnostic.Kind.ERROR,
                    "Failed to emit dependency-access metadata for " + sourceElement.getQualifiedName() + ": "
                            + exception.getMessage(),
                    sourceElement);
        }
    }

    private String getPackageName(TypeElement sourceElement) {
        String qualifiedName = sourceElement.getQualifiedName().toString();
        int lastDotIndex = qualifiedName.lastIndexOf('.');
        if (lastDotIndex < 0) {
            return "";
        }
        return qualifiedName.substring(0, lastDotIndex);
    }
}
